#!/bin/bash
#install Docker
sudo yum update -y
sudo yum install -y docker 
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker ec2-user
sudo chmod 666 /var/run/docker.sock
